services:
  dash-app:
    build: .
    container_name: informe-costos
    expose:
      - "8050"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dash-app